version: '3.11'


services:
  bot:
    build: 
      context: .
    volumes:
      - ./:/code
    
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - db:/var/lib/postgresql/data


volumes:
  db: null