# Generated by Django 5.1.4 on 2024-12-13 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
        ("season", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="season.season",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="season.season",
            ),
        ),
        migrations.DeleteModel(
            name="Season",
        ),
    ]
